matrix:
    include:
        - language: python
          python: "3.7"
          dist: xenial
          os: linux
          env: RUN_LINT=true
        - language: generic
          os: osx
          env: RUN_LINT=false

install:
    - git fetch --unshallow
    - git clone --depth 1 --single-branch https://github.com/thinca/vim-themis && (cd vim-themis && git rev-parse HEAD)
    - mkdir nvim-nightly nvim-stable
    - |
      if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
        curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
        tar xzf nvim-macos.tar.gz -C ./nvim-nightly
        curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim-macos.tar.gz
        tar xzf nvim-macos.tar.gz -C ./nvim-stable
      else
        curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
        tar xzf nvim-linux64.tar.gz -C ./nvim-nightly
        curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
        tar xzf nvim-linux64.tar.gz -C ./nvim-stable

        git clone --depth 1 --single-branch https://github.com/vim/vim /tmp/vim
        cd /tmp/vim
        ./configure --prefix="${HOME}/vim" --with-features=huge --enable-fail-if-missing
        make -j2
        make install
        export PATH=$HOME/vim/bin:$PATH
        cd -
      fi
    - |
      if [[ "$RUN_LINT" == "true" ]]; then
        python3 -V
        pip3 install vim-vint
      fi

before_script:
    - uname -a
    - nvim-nightly/nvim-${TRAVIS_OS_NAME}64/bin/nvim --version
    - nvim-stable/nvim-${TRAVIS_OS_NAME}64/bin/nvim --version
    - vim --version

script:
    - THEMIS_VIM=$(pwd)/nvim-nightly/nvim-${TRAVIS_OS_NAME}64/bin/nvim ./vim-themis/bin/themis ./test/all.vimspec
    - THEMIS_VIM=$(pwd)/nvim-stable/nvim-${TRAVIS_OS_NAME}64/bin/nvim ./vim-themis/bin/themis ./test/all.vimspec
    - THEMIS_VIM=vim ./vim-themis/bin/themis ./test/all.vimspec
    - |
      if [[ "$RUN_LINT" == "true" ]]; then
        vint ./autoload ./plugin
      fi

addons:
    homebrew:
        packages:
            - macvim
        update: true
